### ISSUE TITLE
Fails to run files from its own directory

### ISSUE THREAD

**Issue by zshepherd01** [Joeclinton1/lmc2py#2]
The program fails to open files that are stored in the same directory as the program, unless it is specified with ```./<filename>.ext```
This applies for both .lmc and .txt files.

Terminal output:
```
Traceback (most recent call last):
  File "C:\Users\joesh\Documents\University\Computer Systems\LMC2PY\LMC2PY.py", line 144, in <module>
    lmc = LMC(file_path, 50000)
  File "C:\Users\joesh\Documents\University\Computer Systems\LMC2PY\LMC2PY.py", line 47, in __init__
    self.setup(file_path)
  File "C:\Users\joesh\Documents\University\Computer Systems\LMC2PY\LMC2PY.py", line 53, in setup
    os.chdir(ntpath.dirname(_filepath))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ''
```
(I'd fix it myself now but I'm too tired, I might do it in the morning)

**Comment by Joeclinton1** [comment]
Darius added the `os.chdir(ntpath.dirname(_filepath))` line. I've never used ntpath before.
